import {
  IconAward,
  IconChartHistogram,
  IconClockHour4,
  IconCoin,
  IconPhoneCall,
  IconProgress,
  IconRefresh,
  IconTargetArrow,
  type Icon,
} from "@tabler/icons-react";

/**
 * The nineteen cards of the Workpex Dashboard KPI carousel, in the owner's capture
 * order (DASH-02.2).
 *
 * `counter` is the key the card reads out of `GET /api/dashboard/kpis`. The API
 * implements six of them today; the rest are named here as the backend will name them,
 * and their cards render Unavailable until the response carries the key. Because the
 * carousel asks for *every* counter rather than the ones it knows about, a card starts
 * showing a real figure the day its counter ships — nothing in the frontend changes.
 *
 * Titles and descriptions are the reference's own strings, including its spelling
 * ("Todays", "Followups") — see dashboard-kpi-carousel-cards-*.png.
 */
export interface DashboardKpiCardDef {
  counter: string;
  title: string;
  description: string;
  icon: Icon;
  /** Counts are plain integers; only Converted Amount is money. */
  format?: "count" | "currency";
}

/**
 * Icons come from the installed Tabler set, matched to the reference's glyph *families*
 * — Workpex draws one glyph per metric kind, not per card: a phone-with-star on every
 * lead counter, an axes-and-curve chart on every call counter, a clock on Qualified
 * Leads, circular arrows on both follow-up counters, a bullseye on Target Assigned, a
 * ribbon on both achievement counters and a currency circle on Converted Amount.
 * Tabler has no phone-with-star, so lead counters take `IconPhoneCall`, its nearest
 * phone glyph; nothing here adds an icon dependency (§9).
 */
export const DASHBOARD_KPI_CARDS: readonly DashboardKpiCardDef[] = [
  {
    counter: "leadsThisMonth",
    title: "Leads This Month",
    description: "Total leads assigned this month.",
    icon: IconPhoneCall,
  },
  {
    counter: "todaysLeads",
    title: "Todays Leads",
    description: "Leads assigned today.",
    icon: IconPhoneCall,
  },
  {
    counter: "wonLeads",
    title: "Won Leads",
    description: "Leads converted by you or your team.",
    icon: IconPhoneCall,
  },
  {
    counter: "hotLeads",
    title: "Hot Leads",
    description: "Leads with high conversion potential",
    icon: IconPhoneCall,
  },
  {
    counter: "qualifiedLeads",
    title: "Qualified Leads",
    description: "Leads in Qualified Status.",
    icon: IconClockHour4,
  },
  {
    counter: "noActivityLeads",
    title: "No Activity Leads",
    description: "Leads not attended within 24 hours of assigning.",
    icon: IconPhoneCall,
  },
  {
    counter: "todaysFollowUps",
    title: "Todays Follow Ups",
    description: "Todays scheduled follow-ups",
    icon: IconRefresh,
  },
  {
    counter: "overdueFollowUps",
    title: "Overdue Followups",
    description: "Follow-ups missed their scheduled time.",
    icon: IconRefresh,
  },
  {
    counter: "lostLeads",
    title: "Lost Leads",
    description: "Leads that are in lost status.",
    icon: IconPhoneCall,
  },
  {
    counter: "myLeads",
    title: "My Leads",
    description: "Total Leads assigned to you.",
    icon: IconPhoneCall,
  },
  {
    counter: "callsToday",
    title: "Calls Today",
    description: "Today's Calls.",
    icon: IconChartHistogram,
  },
  {
    counter: "targetAchievedToday",
    title: "Target Achieved Today",
    description: "Number of leads converted by the user today.",
    icon: IconAward,
  },
  {
    counter: "convertedAmount",
    title: "Converted Amount",
    description: "Total conversion value generated by the user.",
    icon: IconCoin,
    format: "currency",
  },
  {
    counter: "inboundCalls",
    title: "Inbound Calls Today",
    description: "Today's Incoming Calls.",
    icon: IconChartHistogram,
  },
  {
    counter: "leadsInPipeline",
    title: "Leads In Pipeline",
    description: "Leads in the Sales Pipeline.",
    icon: IconPhoneCall,
  },
  {
    counter: "outboundCalls",
    title: "Outbound Calls Today",
    description: "Today's Outgoing Calls.",
    icon: IconChartHistogram,
  },
  {
    counter: "targetAssigned",
    title: "Target Assigned",
    description: "Total number of targets assigned to the user.",
    icon: IconTargetArrow,
  },
  {
    counter: "remainingTarget",
    title: "Remaining Target",
    description: "Remaining target yet to be achieved.",
    icon: IconProgress,
  },
  {
    counter: "totalTargetAchieved",
    title: "Total Target Achieved",
    description: "Total number of targets achieved by the user.",
    icon: IconAward,
  },
];

export interface KpiSlotAccent {
  /** Border at full accent strength over a 12 % tint — both measured on the reference. */
  surface: string;
  badge: string;
}

/**
 * The accent for each carousel **slot**, which is how Workpex assigns them — a card
 * keeps the colour of the position it sits in, not one of its own (the evidence is in
 * the `globals.css` accent block). Reordering the cards above therefore reorders the
 * titles, not the colours, exactly as the reference behaves.
 *
 * Slot 8 is the one hue taken from the owner's capture rather than `ui-reference/`:
 * their Overdue Followups card is red where the older capture's slot 8 is purple.
 * Written as whole class strings because Tailwind only emits classes it can see.
 */
export const KPI_SLOT_ACCENTS: readonly KpiSlotAccent[] = [
  {
    surface: "border-accent-orange bg-accent-orange/12",
    badge: "bg-accent-orange",
  },
  { surface: "border-accent-pink bg-accent-pink/12", badge: "bg-accent-pink" },
  { surface: "border-info bg-info/12", badge: "bg-info" },
  {
    surface: "border-accent-violet bg-accent-violet/12",
    badge: "bg-accent-violet",
  },
  { surface: "border-success bg-success/12", badge: "bg-success" },
  { surface: "border-warning bg-warning/12", badge: "bg-warning" },
  {
    surface: "border-accent-yellow bg-accent-yellow/12",
    badge: "bg-accent-yellow",
  },
  { surface: "border-danger bg-danger/12", badge: "bg-danger" },
  { surface: "border-accent-lime bg-accent-lime/12", badge: "bg-accent-lime" },
  { surface: "border-accent-cyan bg-accent-cyan/12", badge: "bg-accent-cyan" },
  {
    surface: "border-accent-forest bg-accent-forest/12",
    badge: "bg-accent-forest",
  },
  {
    surface: "border-accent-indigo bg-accent-indigo/12",
    badge: "bg-accent-indigo",
  },
  { surface: "border-accent-rust bg-accent-rust/12", badge: "bg-accent-rust" },
  {
    surface: "border-accent-magenta bg-accent-magenta/12",
    badge: "bg-accent-magenta",
  },
  {
    surface: "border-accent-emerald bg-accent-emerald/12",
    badge: "bg-accent-emerald",
  },
  { surface: "border-accent-teal bg-accent-teal/12", badge: "bg-accent-teal" },
  {
    surface: "border-accent-periwinkle bg-accent-periwinkle/12",
    badge: "bg-accent-periwinkle",
  },
  { surface: "border-accent-rose bg-accent-rose/12", badge: "bg-accent-rose" },
  {
    surface: "border-accent-orchid bg-accent-orchid/12",
    badge: "bg-accent-orchid",
  },
];
